import images from "./images";

const data = [
  {
    id: 1,
    category: "Web",
    image: images.seeFlix,
    title: "Movie Search Tool",
    desc: "ReactJS | NodeJS | MongoDB",
    demo: "https://seeflix.netlify.app/",
    github: "https://github.com/Juntakk/SeeFlix",
    info: "Movie search platform that allows users to search and view details of thousands of movies. Using the IMDb API, users can browse this site in real time.",
  },
  {
    id: 2,
    category: "Mobile",
    image: images.Image1,
    title: "Reservation App",
    desc: "Java | Android Studio | SQL",
    demo: "",
    github: "https://github.com/Juntakk/Android-Camping-App",
    info: "Activity and field booking application for a camping company, allowing customers to choose from various options based on an SQL database.",
  },
  {
    id: 3,
    category: "Web",
    image: images.Image9,
    title: "E-Commerce",
    desc: "ReactJS | NodeJS | MongoDB",
    demo: "https://steem-frontend.onrender.com/",
    github: "https://github.com/Juntakk/Steem",
    info: "Commerce and management platform that allows users to browse all video games in a Mongoose database, sort them by category, and add them to their wishlist.",
  },
  {
    id: 4,
    category: "Games",
    image: images.Image3,
    title: "Bullet-hell Game",
    desc: "C++ | Godot | GDscript",
    demo: "",
    github: "https://github.com/Juntakk/survivors",
    info: "2D bullet-hell game where the player can choose their character and battlefield. With automatic attacks, they fight hordes of enemies, level up, and improve their skills.",
  },
  {
    id: 5,
    category: "Web",
    image: images.Image8,
    title: "Task Management",
    desc: "ReactJS | CSS | HTML",
    demo: "https://taskbro.netlify.app/",
    github: "https://github.com/Juntakk/taskbro",
    info: "Task and event planner. With basic CRUD features, the user's tasks are saved locally, allowing them to sort, organize by category, and customize the appearance of their page.",
  },
  {
    id: 6,
    category: "Games",
    image: images.Image7,
    title: "RPG game",
    desc: "C++ | Raylib | Unreal Engine",
    demo: "",
    github: "https://github.com/Juntakk/mini-game-3",
    info: "Top-down 2D RPG where the player chooses their character and is thrown into a medieval fantasy world, where they must fight enemies and fill their inventory with powerful items to survive.",
  },
  {
    id: 7,
    category: "Mobile",
    image: images.Image10,
    title: "Learning App",
    desc: "Kotlin | Android Studio | SQL",
    demo: "",
    github: "https://github.com/Juntakk/planetField",
    info: "Educational application about the solar system, where the user is transported to our galaxy and can interact with the planets to learn more about them.",
  },
  {
    id: 8,
    category: "Mobile",
    image: images.Image12,
    title: "Recipe App",
    desc: "Flutter | Riverpod | Clean",
    demo: "",
    github: "https://github.com/Juntakk/meals",
    info: "Meal planning, organization, and recipe search app that allows users to get inspired and manage their diet. They can also sort all recipes in the database to make everything easier.",
  },
  {
    id: 9,
    category: "Mobile",
    image: images.Image13,
    title: "Chat App",
    desc: "Flutter | Riverpod | Clean",
    demo: "",
    github: "https://github.com/Juntakk/chatApp",
    info: "Mobile chat application that allows the user to communicate with other users in the database in real time. They can also delete or modify the messages they have sent.",
  },
  {
    id: 10,
    category: "Mobile",
    image: images.Image14,
    title: "Travel App",
    desc: "Flutter | Bloc | MVC",
    demo: "",
    github: "https://github.com/Juntakk/favoritePlaces",
    info: "Travel application that allows users to take photos, save them in the app with the exact location where they were taken, and all data is stored locally with the help of the Google Maps API.",
  },
  {
    id: 11,
    category: "Mobile",
    image: images.BlogImage,
    title: "Blog App",
    desc: "Flutter | Bloc | Clean",
    demo: "",
    github: "https://github.com/Juntakk/blog_app",
    info: "Blog application using Clean Architecture and Bloc for state management. The user must create an account and log in to view blogs from other users and create, edit, or delete their own.",
  },
];

export default data;
