import images from "./images.js";
import iconsData from "./icons.js";
const { icons, mainIcons } = iconsData;

const data = [
  {
    id: 1,
    category: "Web",
    image: images.ChatImage,
    title: "Chatbot",
    mainIcon: mainIcons.chatbot,
    icons: [icons.python, icons.django, icons.numpy, icons.html],
    screenShot: images.chatbotScreenShot,
    desc: "Python | Django | NumPy",
    demo: "",
    github: "https://github.com/Juntakk/chat-bot",
    info: "Projet d'IA : Je développe un chatbot que j'intégrerai à ce portfolio. J'utilise des outils tels que NumPy, TensorFlow et d'autres bibliothèques. Projet en cours, plus de détails à venir.",
  },
  {
    id: 2,
    category: "Web",
    image: images.seeFlix,
    title: "Seeflix",
    mainIcon: mainIcons.seeFlix,
    icons: [icons.react, icons.node, icons.mongo, icons.tailwind],
    screenShot: images.seeflixScreenshots,
    desc: "ReactJS | NodeJS | MongoDB",
    demo: "https://seeflix.netlify.app/",
    github: "https://github.com/Juntakk/SeeFlix",
    info: "Plateforme de recherche de films, permettant la recherche et le visionnage des détails de milliers de films. Utilisant l'API de IMDB les utilisateurs peuvent parcourir ce site en temps réel.",
  },
  {
    id: 3,
    category: "Web",
    image: images.Image9,
    title: "E-Commerce",
    mainIcon: mainIcons.steem,
    icons: [icons.react, icons.node, icons.mongo, icons.css],
    screenShot: images.steemScreenshots,
    desc: "ReactJS | NodeJS | MongoDB",
    demo: "https://steemgames.netlify.app/",
    github: "https://github.com/Juntakk/steem",
    info: "Plateforme de commerce et de gestion, permet aux utilisateurs de parcourir tous les jeux vidéo dans une base de donnée Mongoose, de trier ceux-ci par catégorie et des les mettre dans leur liste de souhaits.",
  },
  {
    id: 4,
    category: "Jeux",
    image: images.Image3,
    title: "Jeu de Combat",
    mainIcon: mainIcons.survivors,
    icons: [icons.cplusplus, icons.godot],
    screenShot: images.survivorsScreenshots,
    desc: "C++ | Godot | GDscript",
    demo: "",
    github: "https://github.com/Juntakk/survivors",
    info: "Jeu de type bullet-hell en 2D, le joueur peut choisir son personnage et le terrain de combat. Avec des attaques automatiques, il combat des hordes d'ennemis, gagne des niveaux et améliore ses compétences.",
  },
  {
    id: 5,
    category: "Jeux",
    image: images.Image7,
    title: "Mini RPG",
    mainIcon: mainIcons.rpg,
    icons: [icons.cplusplus, icons.raylib, icons.unreal],
    desc: "C++ | Raylib | Unreal Engine",
    demo: "",
    screenShot: images.game3ScreenShot,
    github: "https://github.com/Juntakk/mini-game-3",
    info: "RPG en 2D vu de dessus, le joueur choisit son personnage et est lancé dans un monde médiéval et fantastique où il doit combattre des ennemis, remplir son inventaire d'items puissants pour survivre.",
  },
  {
    id: 6,
    category: "Web",
    image: images.Image12,
    title: "Alimentation",
    mainIcon: mainIcons.recipes,
    icons: [icons.next, icons.tailwind, icons.shadCn],
    desc: "NextJS | Tailwind | Clean",
    screenShot: images.dietAppScreenshot,
    demo: "https://diet-app-ten.vercel.app/",
    github: "https://github.com/Juntakk/diet_app",
    info: "Application web de planification de repas en développement, d'autres fonctionnalités à venir. Application personnelle pour m'aider à mieux gérer mon alimentation et mes courses.",
  },
  {
    id: 7,
    category: "Mobile",
    image: images.BlogImage,
    title: "Blog",
    mainIcon: mainIcons.blog,
    icons: [icons.flutter, icons.dart],
    screenShot: images.blogScreenshot,
    desc: "Flutter | Bloc | Clean",
    demo: "",
    github: "https://github.com/Juntakk/blog_app",
    info: "Application de blogs, en utilisant l'Architecture Clean et Bloc pour la gestion d'état, l'utilisateur doit se créer un compte et se connecter pour visionner des blogs d'autres utilisateurs et créer, modifier et supprimer les siens.",
  },
  {
    id: 8,
    category: "Mobile",
    image: images.favPlaces,
    title: "Souvenirs",
    mainIcon: mainIcons.places,
    icons: [icons.flutter, icons.dart],
    screenShot: images.favPlaces,
    desc: "",
    demo: "",
    github: "https://github.com/Juntakk/favorite-places",
    info: "Application de voyage utilisant l'API Google Maps et la fonctionnalité photo pour capturer des souvenirs et sauvegarder leur emplacement sur la carte. Développée avec l'Architecture Clean et Bloc pour la gestion d'état.",
  },
];

export default data;
