import images from "./images.js";
import icons from "./icons.js";

const data = [
  {
    id: 1,
    category: "Web",
    image: images.ChatImage,
    title: "Chatbot",
    icons: [icons.python, icons.django, icons.numpy, icons.html],
    screenShot: images.chatbotScreenShot,
    desc: "Python | Django | NumPy",
    demo: "",
    github: "https://github.com/Juntakk/chat-bot",
    info: "Projet d'IA : Je développe un chatbot que j'intégrerai à ce portfolio. J'utilise des outils tels que NumPy, TensorFlow et d'autres bibliothèques. Projet en cours, plus de détails à venir.",
  },
  {
    id: 2,
    category: "Web",
    image: images.seeFlix,
    title: "Seeflix",
    icons: [icons.react, icons.node, icons.mongo, icons.tailwind],
    screenShot: images.seeflixScreenshots,
    desc: "ReactJS | NodeJS | MongoDB",
    demo: "https://seeflix.netlify.app/",
    github: "https://github.com/Juntakk/SeeFlix",
    info: "Plateforme de recherche de films, permettant la recherche et le visionnage des détails de milliers de films. Utilisant l'API de IMDB les utilisateurs peuvent parcourir ce site en temps réel.",
  },
  //   {
  //     id: 3,
  //     category: "Mobile",
  //     image: images.Image1,
  //     title: "Application d'entreprise",
  //     icons: [icons.java, icons.sql, icons.android],

  //     desc: "Java | Android Studio | SQL",
  //     demo: "",
  //     github: "https://github.com/Juntakk/Android-Camping-App",
  //     info: "Application de réservation d'activités et de terrains pour une entreprise de camping, permet aux clients de choisir parmi plusieurs choix à partir d'une base de données SQL.",
  //   },
  {
    id: 3,
    category: "Web",
    image: images.Image9,
    title: "E-Commerce",
    icons: [icons.react, icons.node, icons.mongo, icons.css],
    screenShot: images.steemScreenshots,
    desc: "ReactJS | NodeJS | MongoDB",
    demo: "https://steemgames.netlify.app/",
    github: "https://github.com/Juntakk/steem",
    info: "Plateforme de commerce et de gestion, permet aux utilisateurs de parcourir tous les jeux vidéo dans une base de donnée Mongoose, de trier ceux-ci par catégorie et des les mettre dans leur liste de souhaits.",
  },
  {
    id: 4,
    category: "Jeux",
    image: images.Image3,
    title: "Jeu de Combat",
    icons: [icons.cplusplus, icons.godot],
    screenShot: images.survivorsScreenshots,
    desc: "C++ | Godot | GDscript",
    demo: "",
    github: "https://github.com/Juntakk/survivors",
    info: "Jeu de type bullet-hell en 2D, le joueur peut choisir son personnage et le terrain de combat. Avec des attaques automatiques, il combat des hordes d'ennemis, gagne des niveaux et améliore ses compétences.",
  },
  // {
  //   id: 5,
  //   category: "Web",
  //   image: images.Image8,
  //   title: "Gestion des tâches",
  //   desc: "ReactJS | CSS | HTML",
  //   demo: "https://taskbro.netlify.app/",
  //   github: "https://github.com/Juntakk/taskbro",
  //   info: "Planificateur de tâches et d'événements. Avec des fonctionnalités CRUD de base, les tâches de l'utilisateur sont sauvegardées localement, il peut les trier, les organiser par catégorie et modifier l'apparence de sa page.",
  // },
  {
    id: 5,
    category: "Jeux",
    image: images.Image7,
    title: "Mini RPG",
    icons: [icons.cplusplus, icons.raylib, icons.unreal],
    desc: "C++ | Raylib | Unreal Engine",
    demo: "",
    screenShot: images.game3ScreenShot,
    github: "https://github.com/Juntakk/mini-game-3",
    info: "RPG en 2D vu de dessus, le joueur choisit son personnage et est lancé dans un monde médiéval et fantastique où il doit combattre des ennemis, remplir son inventaire d'items puissants pour survivre.",
  },
  // {
  //   id: 7,
  //   category: "Mobile",
  //   image: images.Image10,
  //   title: "Application d'apprentissage",
  //   desc: "Kotlin | Android Studio | SQL ",
  //   demo: "",
  //   github: "https://github.com/Juntakk/planetField",
  //   info: "Application éducative sur le système solaire, l'utilisateur se voit transporter dans notre galaxie où il peut interagir avec nos planètes pour en apprendre davantage sur celles-ci.",
  // },
  {
    id: 6,
    category: "Mobile",
    image: images.Image12,
    title: "Recettes",
    icons: [icons.flutter, icons.dart],
    screenShot: images.mealsScreenshot,
    desc: "Flutter | Riverpod | Clean",
    demo: "",
    github: "https://github.com/Juntakk/meals",
    info: "Planification de repas, organisation et recherche de recettes, cette application permet à l'utilisateur de s'inspirer et de contrôler son alimentation. Il peut aussi trier toutes les recettes dans la BDD pour faciliter le tout.",
  },
  // {
  //   id: 9,
  //   category: "Mobile",
  //   image: images.Image13,
  //   title: "Clône Messenger",
  //   desc: "Flutter | Riverpod | Clean",
  //   demo: "",
  //   github: "https://github.com/Juntakk/chatApp",
  //   info: "Application de chat mobile permettant à l'utilisateur de communiquer avec notre utilisateurs présents dans la BDD en temps réel. Il peut aussi supprimer ou modifier les messages qu'il a envoyé.",
  // },
  {
    id: 7,
    category: "Mobile",
    image: images.Image14,
    title: "Voyages",
    icons: [icons.flutter, icons.dart],
    screenShot: images.placesScreenShot,
    desc: "Flutter | Bloc | MVC",
    demo: "",
    github: "https://github.com/Juntakk/favoritePlaces",
    info: "Application de voyage permettant aux utilisateurs de prendre des photo, de les sauvegarder dans l'application avec l'endroit exact qu'elles ont été prises et le tout est sauvegarder localement avec l'aide de l'API Google Maps.",
  },
  {
    id: 8,
    category: "Mobile",
    image: images.BlogImage,
    title: "Blog",
    icons: [icons.flutter, icons.dart],
    screenShot: images.blogScreenshot,
    desc: "Flutter | Bloc | Clean",
    demo: "",
    github: "https://github.com/Juntakk/blog_app",
    info: "Application de blogs, en utilisant l'Architecture Clean et Bloc pour la gestion d'état, l'utilisateur doit se créer un compte et se connecter pour visionner des blogs d'autres utilisateurs et créer, modifier et supprimer les siens.",
  },
];

export default data;
